name: metalearn_0.0.5_config_0.0.1
experiment_type: METALEARN_REINFORCE
description: |
  metalearn-0.0.5 tuning experiment:
  * double the capacity network depth- and breadth-wise.
  * Increase dropout rate to 0.3
  * Introduce 0.1 entropy_coef (increasing encourages exploration)
created_at: 2019-07-02-23-21-00
git_hash: b570f88
parameters:
  datasets: null
  output_fp: /output
  n_trials: 1
  input_size: 60
  hidden_size: 60
  output_size: 60
  n_layers: 6
  dropout_rate: 0.3
  beta: 0.9
  entropy_coef: 0.1
  with_baseline: true
  single_baseline: true
  normalize_reward: false
  n_episodes: 500
  n_iter: 16
  learning_rate: 0.005
  env_sources:
  - SKLEARN
  - OPEN_ML
  - KAGGLE
  target_types:
  - BINARY
  - MULTICLASS
  - MULTIREGRESSION
  test_set_config:
    SKLEARN:
      test_size: 0.8
      random_state: 100
    OPEN_ML:
      test_size: 0.8
      random_state: 54321
    KAGGLE:
      test_size: 0.8
      random_state: 9000
  error_reward: 0
  n_samples: 5000
  per_framework_time_limit: 180
  per_framework_memory_limit: 5000
  metric_logger: floyd
  fit_verbose: 0
  controller_seed: 1000
  task_environment_seed: 100
