name: train_sklearn_for_inference_0a
description: test run new API with inference engine
created_at: 2018-12-09-23:01:12
git_hash: 2bcfaaf
parameters:
  datasets: null
  output_fp: /output
  n_trials: 1
  input_size: 30
  hidden_size: 30
  output_size: 30
  n_layers: 3
  dropout_rate: 0.2
  beta: 0.9
  entropy_coef: 0.02
  with_baseline: true
  single_baseline: true
  normalize_reward: false
  n_episodes: 300
  n_iter: 16
  learning_rate: 0.005
  env_sources:
  - SKLEARN
  target_types:
  - BINARY
  - MULTICLASS
  error_reward: 0
  per_framework_time_limit: 180
  per_framework_memory_limit: 5000
  metric_logger: floyd
  fit_verbose: 0
  controller_seed: 1000
  task_environment_seed: 100
