name: kaggle_regression_exp_1a
description: kaggle regression experiment
created_at: 2018-10-16-22:21:44
git_hash: 9b43c75
parameters:
  datasets:
  - "restaurant_revenue_prediction"
  - "nyc_taxi_trip_duration"
  - "mercedes_benz_greener_manufacturing"
  - "allstate_claims_severity"
  - "house_prices_advanced_regression_techniques"
  output_fp: /output
  n_trials: 1
  input_size: 30
  hidden_size: 30
  output_size: 30
  n_layers: 3
  dropout_rate: 0.2
  beta: 0.9
  entropy_coef: 0.02
  with_baseline: true
  single_baseline: true
  normalize_reward: false
  n_episodes: 1009
  n_iter: 16
  learning_rate: 0.005
  target_types:
  - REGRESSION
  error_reward: 0
  per_framework_time_limit: 180
  per_framework_memory_limit: 5000
  metric_logger: floyd
  fit_verbose: 0
  controller_seed: 1000
  task_environment_seed: 100
