name: regression_exp_1
description: regression experiment with new cli commands
created_at: 2018-09-23-21:56:30
git_hash: fe5e7ed
parameters:
  datasets: null
  output_fp: /output
  n_trials: 1
  input_size: 30
  hidden_size: 30
  output_size: 30
  n_layers: 3
  dropout_rate: 0.2
  beta: 0.9
  entropy_coef: 0.0
  with_baseline: true
  single_baseline: true
  normalize_reward: false
  n_episodes: 100
  n_iter: 16
  learning_rate: 0.005
  target_types:
  - REGRESSION
  error_reward: 0
  per_framework_time_limit: 180
  per_framework_memory_limit: 5000
  metric_logger: floyd
  fit_verbose: 0
  controller_seed: 1000
  task_environment_seed: 100
