name: kaggle_homesite_quote_conversion
description: ''
created_at: 2018-10-22-23:00:22
git_hash: 734ea1a
parameters:
  datasets:
  - "homesite_quote_conversion"
  output_fp: /output
  n_trials: 1
  input_size: 30
  hidden_size: 30
  output_size: 30
  n_layers: 3
  dropout_rate: 0.2
  beta: 0.9
  entropy_coef: 0.0
  with_baseline: true
  single_baseline: true
  normalize_reward: false
  n_episodes: 300
  n_iter: 16
  learning_rate: 0.005
  env_sources:
  - KAGGLE
  target_types:
  - BINARY
  - MULTICLASS
  error_reward: 0
  per_framework_time_limit: 540
  per_framework_memory_limit: 10000
  metric_logger: floyd
  fit_verbose: 1
  controller_seed: 1000
  task_environment_seed: 100
