name: regression_exp_5
description: >
  remove entropy coef, see if model improves. Based on observations made over
  https://www.floydhub.com/nielsbantilan/projects/deep-cash/197. It seems like
  the model is not converging on a smaller set of MLFs. This might be because
  the entropy coef is highly sensitive to the size of the search space. Job 197
  was the first to train the controller over 14 regressors, whereas the
  previous classification experiments only had a search space of 3 classifiers
  to search through. Want to see if reducing `entropy_coef` to 0 will help
  the controller find optimal models. The next experiment should also verify
  whether the search space hypothesis is true, but for classifiers.
created_at: 2018-10-03-21:59:57
git_hash: d5fdaf1
parameters:
  datasets: null
  output_fp: /output
  n_trials: 1
  input_size: 30
  hidden_size: 30
  output_size: 30
  n_layers: 3
  dropout_rate: 0.2
  beta: 0.9
  entropy_coef: 0.0
  with_baseline: true
  single_baseline: true
  normalize_reward: false
  n_episodes: 2000
  n_iter: 16
  learning_rate: 0.005
  target_types:
  - REGRESSION
  error_reward: 0
  per_framework_time_limit: 180
  per_framework_memory_limit: 5000
  metric_logger: floyd
  fit_verbose: 0
  controller_seed: 1000
  task_environment_seed: 100
