name: kaggle_classification_poker_rule_induction_exp_1a
description: poker rule induction training
created_at: 2018-11-11-15:35:19
git_hash: 13b4bc5
parameters:
  datasets:
  - "poker_rule_induction"
  output_fp: /output
  n_trials: 1
  input_size: 30
  hidden_size: 30
  output_size: 30
  n_layers: 3
  dropout_rate: 0.2
  beta: 0.9
  entropy_coef: 0.0
  with_baseline: true
  single_baseline: true
  normalize_reward: false
  n_episodes: 100
  n_iter: 16
  learning_rate: 0.005
  env_sources:
  - KAGGLE
  target_types:
  - BINARY
  - MULTICLASS
  error_reward: 0
  per_framework_time_limit: 540
  per_framework_memory_limit: 10000
  metric_logger: floyd
  fit_verbose: 0
  controller_seed: 1000
  task_environment_seed: 100
