name: random_search_autosklearn_benchmark_dataset_0
experiment_type: RANDOM_SEARCH
description: test random search fitter on the autosklearn datasets
created_at: 2019-01-27-22-17-40
git_hash: c36f5aa
parameters:
  datasets: null
  output_fp: /output
  n_trials: 3
  n_episodes: 300
  n_iter: 16
  env_sources:
  - AUTOSKLEARN_BENCHMARK
  target_types:
  - BINARY
  - MULTICLASS
  - REGRESSION
  test_set_config: null
  error_reward: 0
  n_samples: 10000
  per_framework_time_limit: 180
  per_framework_memory_limit: 5000
  metric_logger: floyd
  fit_verbose: 0
  controller_seed: 1000
  task_environment_seed: 100
