name: local_serialization_experiment
experiment_type: METALEARN_REINFORCE
description: null
created_at: 2019-10-27-21-04-21
git_hash: f68b6e5
parameters:
  datasets:
  - sklearn.iris
  - sklearn.digits
  - sklearn.wine
  - sklearn.breast_cancer
  test_datasets:
  - openml.letter
  - openml.mfeat-morphological
  - openml.car
  output_fp: ./output
  input_size: 32
  hidden_size: 32
  output_size: 32
  n_layers: 5
  dropout_rate: 0.3
  beta: 0.9
  entropy_coef: 1.0
  entropy_coef_anneal_to: 0.01
  entropy_coef_anneal_by: 1.0
  with_baseline: true
  single_baseline: false
  normalize_reward: true
  n_episodes: 2
  n_iter: 8
  learning_rate: 0.005
  env_sources:
  - SKLEARN
  test_env_sources:
  - AUTOSKLEARN_BENCHMARK
  n_eval_iter: 3
  target_types:
  - BINARY
  test_set_config:
    SKLEARN:
      test_size: 0.2
      random_state: 100
    AUTOSKLEARN_BENCHMARK:
      test_size: 0.2
      random_state: 100
  error_reward: 0
  n_samples: 2000
  per_framework_time_limit: 360
  per_framework_memory_limit: 5000
  metric_logger: null
  fit_verbose: 1
  controller_seed: 1000
  task_environment_seed: 100
  hyperparameters:
    entropy_coef:
    - 0.0
    - 0.2
    - 0.4
    meta_reward_multiplier:
    - 1.0
    learning_rate:
    - 0.005
